name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
          ssh user@https://be4d-102-91-105-156.ngrok-free.app << 'EOF'
          cd "C:/Users/user/Desktop/fastapi-book-project"
          git pull origin main
          pip install -r requirements.txt
          pm2 restart fastapi-app
          docker-compose up --build -d
          EOF