name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
          ssh user127.0.0.1:8000 << 'EOF'
          cd C:/Users/user/Desktop/
          
          # Clone the repo if it doesn't exist
          if [ ! -d "fastapi-book-project" ]; then
            git clone https://github.com/rillygulma/HNG12-BACKEND-TASK-TWO.git fastapi-book-project
          fi
          
          cd fastapi-book-project
          git pull origin main
          pip install -r requirements.txt
          pm2 restart fastapi-app
          EOF
