name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
          ssh user@192.168.0.148 << 'EOF'
          cd "C:/Users/user/Desktop/fastapi-book-project"
          git pull origin main
          docker-compose up --build -d
          EOF